### PR TITLE
Some loading optimizations

### PR DESCRIPTION
**Pull request by jeffbcross**
I included some quick wins to improve the application's loading performance. Each commit has a detailed description of what was done, and why. Here's a quick overview:

 * Remove redundant CSS rules that were ending up in every component
 * Remove lazy loading of feed route
 * Remove some unneeded packages from production build
 * Use a smaller fetch polyfill
 * Reduce bundles to single bundle which is loaded with `async` attribute.

Paired with @mgechev on these yesterday.

I have a separate branch where I'm pre-rendering the app-shell with webpack and @angular/platform-server, and have some other ideas how to leverage pre-rendering at runtime as well, which I'll chat with you about.

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Can't thank you and @mgechev enough for this. You've spotted so many small quick wins throughout the entire app which is amazing 🙌 .

Also thank you for detailing every single commit with a nice description ☺️. I appreciate you taking the time to do that, it made it so much easier to understand what this PR included.

**Comment by addyosmani** [comment]
Epic work, @jeffbcross! 🎉 

@housseindjirdeh is this deployed on production now?

**Comment by MarkPieszak** [comment]
This looks fantastic guys! @jeffbcross :1st_place_medal: 
How is the TTI looking now?

:champagne:

**Comment by mgechev** [comment]
@addyosmani with @jeffbcross we were testing it [here](https://ng-hn-pwa-1e5ff.firebaseapp.com/news/1).

With my local Lighthouse, I get decent results. There are still a few minor things which can tune the performance further.

screen shot 2017-06-02 at 20 31 58

**Comment by jeffbcross** [comment]
Worth noting: last night we were testing with app shell pre-rendering, which I haven't included in this PR because I'm working on publishing a package to npm to abstract away most of the config boilerplate.

**Comment by housseindjirdeh** [comment]
@addyosmani it is deployed to [production](https://angular2-hn.firebaseapp.com)!

Lighthouse performance results are looking quite better on my end actually

screen shot 2017-06-03 at 12 08 01 am

Did a couple of WPT runs as well but unfortunately `First Interactive` results aren't being displayed through their linked Lighthouse results (might be a bug?). Will definitely do a couple more runs tomorrow however. @MarkPieszak

**Comment by addyosmani** [comment]
There were some bugs in there earlier today that we deployed a fix for. Let me know if it's still borked in the morning and we can chase.

**Pull request merged**
